# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'loginwidget_2.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Login(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(419, 293)
        palette = QPalette()
        brush = QBrush(QColor(85, 87, 83, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(53, 53, 53, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ID_lineedit = QLineEdit(self.centralwidget)
        self.ID_lineedit.setObjectName(u"ID_lineedit")
        self.ID_lineedit.setGeometry(QRect(50, 70, 301, 41))
        palette1 = QPalette()
        brush2 = QBrush(QColor(238, 238, 236, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush3 = QBrush(QColor(136, 138, 133, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(238, 238, 236, 128))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        brush5 = QBrush(QColor(190, 190, 190, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush6 = QBrush(QColor(0, 0, 0, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.ID_lineedit.setPalette(palette1)
        font1 = QFont()
        font1.setPointSize(11)
        self.ID_lineedit.setFont(font1)
        self.pw_lineedit = QLineEdit(self.centralwidget)
        self.pw_lineedit.setObjectName(u"pw_lineedit")
        self.pw_lineedit.setGeometry(QRect(50, 120, 301, 41))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.pw_lineedit.setPalette(palette2)
        self.pw_lineedit.setFont(font1)
        self.sign_in_label = QLabel(self.centralwidget)
        self.sign_in_label.setObjectName(u"sign_in_label")
        self.sign_in_label.setGeometry(QRect(50, 30, 191, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush7 = QBrush(QColor(255, 255, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush7)
        brush8 = QBrush(QColor(255, 255, 255, 128))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.sign_in_label.setPalette(palette3)
        font2 = QFont()
        font2.setFamily(u"Noto Sans CJK JP")
        font2.setPointSize(17)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setWeight(75)
        self.sign_in_label.setFont(font2)
        self.signin_btn = QPushButton(self.centralwidget)
        self.signin_btn.setObjectName(u"signin_btn")
        self.signin_btn.setGeometry(QRect(50, 220, 301, 41))
        palette4 = QPalette()
        brush9 = QBrush(QColor(252, 175, 62, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush9)
        brush10 = QBrush(QColor(48, 140, 198, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush11 = QBrush(QColor(145, 145, 145, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Disabled, QPalette.Highlight, brush11)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.signin_btn.setPalette(palette4)
        font3 = QFont()
        font3.setPointSize(13)
        font3.setBold(True)
        font3.setWeight(75)
        self.signin_btn.setFont(font3)
        self.error_label = QLabel(self.centralwidget)
        self.error_label.setObjectName(u"error_label")
        self.error_label.setGeometry(QRect(50, 160, 311, 20))
        palette5 = QPalette()
        brush12 = QBrush(QColor(237, 90, 32, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush12)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush12)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        self.error_label.setPalette(palette5)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(50, 180, 331, 39))
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.remember_checkbox = QCheckBox(self.widget)
        self.remember_checkbox.setObjectName(u"remember_checkbox")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        self.remember_checkbox.setPalette(palette6)
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        font4.setWeight(50)
        self.remember_checkbox.setFont(font4)

        self.horizontalLayout.addWidget(self.remember_checkbox)

        self.forgotpw_cmdlinkbtn = QCommandLinkButton(self.widget)
        self.forgotpw_cmdlinkbtn.setObjectName(u"forgotpw_cmdlinkbtn")
        self.forgotpw_cmdlinkbtn.setEnabled(True)
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.forgotpw_cmdlinkbtn.setPalette(palette7)
        self.forgotpw_cmdlinkbtn.setFont(font4)

        self.horizontalLayout.addWidget(self.forgotpw_cmdlinkbtn)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ID_lineedit.setText("")
        self.sign_in_label.setText(QCoreApplication.translate("MainWindow", u"KITSU SIGN IN", None))
        self.signin_btn.setText(QCoreApplication.translate("MainWindow", u"SIGN IN", None))
        self.error_label.setText(QCoreApplication.translate("MainWindow", u"Error message Error message Error msg", None))
        self.remember_checkbox.setText(QCoreApplication.translate("MainWindow", u"Remember Me", None))
        self.forgotpw_cmdlinkbtn.setText(QCoreApplication.translate("MainWindow", u"Forgot Password?", None))
    # retranslateUi

