# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'nuki_main_widget_1.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Nuki(object):
    def setupUi(self, Nuki):
        if not Nuki.objectName():
            Nuki.setObjectName(u"Nuki")
        Nuki.setWindowModality(Qt.NonModal)
        Nuki.resize(1337, 582)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Nuki.sizePolicy().hasHeightForWidth())
        Nuki.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(53, 53, 53, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        Nuki.setPalette(palette)
        self.layoutWidget = QWidget(Nuki)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(190, 10, 761, 541))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(-1, -1, 170, -1)
        self.assigned_shot_label = QLabel(self.layoutWidget)
        self.assigned_shot_label.setObjectName(u"assigned_shot_label")
        palette1 = QPalette()
        brush2 = QBrush(QColor(238, 238, 236, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush3 = QBrush(QColor(238, 238, 236, 128))
        brush3.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        brush4 = QBrush(QColor(190, 190, 190, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        brush5 = QBrush(QColor(0, 0, 0, 128))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.assigned_shot_label.setPalette(palette1)

        self.horizontalLayout_4.addWidget(self.assigned_shot_label)

        self.assigned_shot_num = QLabel(self.layoutWidget)
        self.assigned_shot_num.setObjectName(u"assigned_shot_num")
        sizePolicy.setHeightForWidth(self.assigned_shot_num.sizePolicy().hasHeightForWidth())
        self.assigned_shot_num.setSizePolicy(sizePolicy)
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.assigned_shot_num.setPalette(palette2)

        self.horizontalLayout_4.addWidget(self.assigned_shot_num)


        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)

        self.sorted_label = QLabel(self.layoutWidget)
        self.sorted_label.setObjectName(u"sorted_label")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.sorted_label.sizePolicy().hasHeightForWidth())
        self.sorted_label.setSizePolicy(sizePolicy1)
        self.sorted_label.setMinimumSize(QSize(60, 0))
        self.sorted_label.setMaximumSize(QSize(200, 16777215))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.sorted_label.setPalette(palette3)
        font = QFont()
        font.setFamily(u"Carlito")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sorted_label.setFont(font)
        self.sorted_label.setLayoutDirection(Qt.RightToLeft)
        self.sorted_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.sorted_label)

        self.sorted_comboBox = QComboBox(self.layoutWidget)
        self.sorted_comboBox.addItem("")
        self.sorted_comboBox.addItem("")
        self.sorted_comboBox.addItem("")
        self.sorted_comboBox.setObjectName(u"sorted_comboBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.sorted_comboBox.sizePolicy().hasHeightForWidth())
        self.sorted_comboBox.setSizePolicy(sizePolicy2)
        self.sorted_comboBox.setMinimumSize(QSize(150, 27))
        palette4 = QPalette()
        brush6 = QBrush(QColor(238, 173, 83, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush6)
        brush7 = QBrush(QColor(145, 145, 145, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        self.sorted_comboBox.setPalette(palette4)
        font1 = QFont()
        font1.setFamily(u"Cantarell")
        font1.setPointSize(11)
        font1.setBold(False)
        font1.setWeight(50)
        self.sorted_comboBox.setFont(font1)
        self.sorted_comboBox.setLayoutDirection(Qt.LeftToRight)
        self.sorted_comboBox.setAutoFillBackground(False)
        self.sorted_comboBox.setStyleSheet(u"QComboBox:hover {\n"
"border-style: outset;\n"
"border-radius: 5px;\n"
"border: 3px solid rgb(238, 173, 83);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    selection-background-color: rgb(238, 173, 83);\n"
"}\n"
"")
        self.sorted_comboBox.setFrame(False)

        self.horizontalLayout_3.addWidget(self.sorted_comboBox)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.shot_list = QListView(self.layoutWidget)
        self.shot_list.setObjectName(u"shot_list")

        self.verticalLayout.addWidget(self.shot_list)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.thumbnail_label = QLabel(self.layoutWidget)
        self.thumbnail_label.setObjectName(u"thumbnail_label")
        sizePolicy1.setHeightForWidth(self.thumbnail_label.sizePolicy().hasHeightForWidth())
        self.thumbnail_label.setSizePolicy(sizePolicy1)
        self.thumbnail_label.setMinimumSize(QSize(300, 200))
        self.thumbnail_label.setMaximumSize(QSize(350, 200))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.thumbnail_label.setPalette(palette5)
        self.thumbnail_label.setFrameShape(QFrame.Box)
        self.thumbnail_label.setLineWidth(0)
        self.thumbnail_label.setScaledContents(False)
        self.thumbnail_label.setAlignment(Qt.AlignCenter)
        self.thumbnail_label.setMargin(0)
        self.thumbnail_label.setIndent(-1)

        self.horizontalLayout_2.addWidget(self.thumbnail_label)

        self.gridLayout = QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label_shot = QLabel(self.layoutWidget)
        self.label_shot.setObjectName(u"label_shot")
        sizePolicy2.setHeightForWidth(self.label_shot.sizePolicy().hasHeightForWidth())
        self.label_shot.setSizePolicy(sizePolicy2)
        font2 = QFont()
        font2.setFamily(u"Carlito")
        font2.setPointSize(12)
        font2.setBold(False)
        font2.setWeight(50)
        self.label_shot.setFont(font2)
        self.label_shot.setFrameShape(QFrame.NoFrame)
        self.label_shot.setMargin(3)

        self.gridLayout.addWidget(self.label_shot, 2, 1, 1, 2)

        self.revision = QLabel(self.layoutWidget)
        self.revision.setObjectName(u"revision")
        sizePolicy2.setHeightForWidth(self.revision.sizePolicy().hasHeightForWidth())
        self.revision.setSizePolicy(sizePolicy2)
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.revision.setPalette(palette6)
        self.revision.setFont(font)
        self.revision.setLayoutDirection(Qt.RightToLeft)
        self.revision.setFrameShape(QFrame.NoFrame)
        self.revision.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.revision.setMargin(3)

        self.gridLayout.addWidget(self.revision, 6, 0, 1, 1)

        self.resolution = QLabel(self.layoutWidget)
        self.resolution.setObjectName(u"resolution")
        sizePolicy2.setHeightForWidth(self.resolution.sizePolicy().hasHeightForWidth())
        self.resolution.setSizePolicy(sizePolicy2)
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.resolution.setPalette(palette7)
        self.resolution.setFont(font)
        self.resolution.setLayoutDirection(Qt.RightToLeft)
        self.resolution.setFrameShape(QFrame.NoFrame)
        self.resolution.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.resolution.setMargin(3)

        self.gridLayout.addWidget(self.resolution, 4, 0, 1, 1)

        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.label_frame_in = QLabel(self.layoutWidget)
        self.label_frame_in.setObjectName(u"label_frame_in")
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_frame_in.sizePolicy().hasHeightForWidth())
        self.label_frame_in.setSizePolicy(sizePolicy3)
        self.label_frame_in.setMinimumSize(QSize(0, 0))
        self.label_frame_in.setFont(font2)
        self.label_frame_in.setFrameShape(QFrame.NoFrame)
        self.label_frame_in.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_frame_in.setMargin(3)

        self.horizontalLayout_10.addWidget(self.label_frame_in)

        self.label_frame_out = QLabel(self.layoutWidget)
        self.label_frame_out.setObjectName(u"label_frame_out")
        sizePolicy3.setHeightForWidth(self.label_frame_out.sizePolicy().hasHeightForWidth())
        self.label_frame_out.setSizePolicy(sizePolicy3)
        self.label_frame_out.setMinimumSize(QSize(0, 0))
        self.label_frame_out.setFont(font2)
        self.label_frame_out.setFrameShape(QFrame.NoFrame)
        self.label_frame_out.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_frame_out.setMargin(3)

        self.horizontalLayout_10.addWidget(self.label_frame_out)


        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 1, 1, 2)

        self.label_resolution = QLabel(self.layoutWidget)
        self.label_resolution.setObjectName(u"label_resolution")
        sizePolicy2.setHeightForWidth(self.label_resolution.sizePolicy().hasHeightForWidth())
        self.label_resolution.setSizePolicy(sizePolicy2)
        self.label_resolution.setFont(font2)
        self.label_resolution.setFrameShape(QFrame.NoFrame)
        self.label_resolution.setMargin(3)

        self.gridLayout.addWidget(self.label_resolution, 4, 1, 1, 2)

        self.label_proj = QLabel(self.layoutWidget)
        self.label_proj.setObjectName(u"label_proj")
        sizePolicy2.setHeightForWidth(self.label_proj.sizePolicy().hasHeightForWidth())
        self.label_proj.setSizePolicy(sizePolicy2)
        font3 = QFont()
        font3.setFamily(u"Carlito")
        font3.setPointSize(12)
        self.label_proj.setFont(font3)
        self.label_proj.setFrameShape(QFrame.NoFrame)
        self.label_proj.setMargin(3)

        self.gridLayout.addWidget(self.label_proj, 0, 1, 1, 2)

        self.frame_range = QLabel(self.layoutWidget)
        self.frame_range.setObjectName(u"frame_range")
        sizePolicy3.setHeightForWidth(self.frame_range.sizePolicy().hasHeightForWidth())
        self.frame_range.setSizePolicy(sizePolicy3)
        self.frame_range.setMinimumSize(QSize(142, 0))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.frame_range.setPalette(palette8)
        self.frame_range.setFont(font)
        self.frame_range.setLayoutDirection(Qt.RightToLeft)
        self.frame_range.setFrameShape(QFrame.NoFrame)
        self.frame_range.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.frame_range.setMargin(3)

        self.gridLayout.addWidget(self.frame_range, 3, 0, 1, 1)

        self.label_fps = QLabel(self.layoutWidget)
        self.label_fps.setObjectName(u"label_fps")
        sizePolicy2.setHeightForWidth(self.label_fps.sizePolicy().hasHeightForWidth())
        self.label_fps.setSizePolicy(sizePolicy2)
        self.label_fps.setFont(font2)
        self.label_fps.setFrameShape(QFrame.NoFrame)
        self.label_fps.setMargin(3)

        self.gridLayout.addWidget(self.label_fps, 5, 1, 1, 2)

        self.label_seq = QLabel(self.layoutWidget)
        self.label_seq.setObjectName(u"label_seq")
        sizePolicy2.setHeightForWidth(self.label_seq.sizePolicy().hasHeightForWidth())
        self.label_seq.setSizePolicy(sizePolicy2)
        self.label_seq.setFont(font2)
        self.label_seq.setFrameShape(QFrame.NoFrame)
        self.label_seq.setMargin(3)

        self.gridLayout.addWidget(self.label_seq, 1, 1, 1, 2)

        self.label_revision = QLabel(self.layoutWidget)
        self.label_revision.setObjectName(u"label_revision")
        sizePolicy2.setHeightForWidth(self.label_revision.sizePolicy().hasHeightForWidth())
        self.label_revision.setSizePolicy(sizePolicy2)
        self.label_revision.setFont(font2)
        self.label_revision.setFrameShape(QFrame.NoFrame)
        self.label_revision.setFrameShadow(QFrame.Plain)
        self.label_revision.setMargin(3)

        self.gridLayout.addWidget(self.label_revision, 6, 1, 1, 2)

        self.sequence = QLabel(self.layoutWidget)
        self.sequence.setObjectName(u"sequence")
        sizePolicy2.setHeightForWidth(self.sequence.sizePolicy().hasHeightForWidth())
        self.sequence.setSizePolicy(sizePolicy2)
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.sequence.setPalette(palette9)
        self.sequence.setFont(font)
        self.sequence.setLayoutDirection(Qt.RightToLeft)
        self.sequence.setFrameShape(QFrame.NoFrame)
        self.sequence.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.sequence.setMargin(3)

        self.gridLayout.addWidget(self.sequence, 1, 0, 1, 1)

        self.shot = QLabel(self.layoutWidget)
        self.shot.setObjectName(u"shot")
        sizePolicy2.setHeightForWidth(self.shot.sizePolicy().hasHeightForWidth())
        self.shot.setSizePolicy(sizePolicy2)
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.shot.setPalette(palette10)
        self.shot.setFont(font)
        self.shot.setLayoutDirection(Qt.RightToLeft)
        self.shot.setFrameShape(QFrame.NoFrame)
        self.shot.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.shot.setMargin(3)

        self.gridLayout.addWidget(self.shot, 2, 0, 1, 1)

        self.fps = QLabel(self.layoutWidget)
        self.fps.setObjectName(u"fps")
        sizePolicy2.setHeightForWidth(self.fps.sizePolicy().hasHeightForWidth())
        self.fps.setSizePolicy(sizePolicy2)
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.fps.setPalette(palette11)
        self.fps.setFont(font)
        self.fps.setLayoutDirection(Qt.RightToLeft)
        self.fps.setFrameShape(QFrame.NoFrame)
        self.fps.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.fps.setMargin(3)

        self.gridLayout.addWidget(self.fps, 5, 0, 1, 1)

        self.project = QLabel(self.layoutWidget)
        self.project.setObjectName(u"project")
        sizePolicy2.setHeightForWidth(self.project.sizePolicy().hasHeightForWidth())
        self.project.setSizePolicy(sizePolicy2)
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.project.setPalette(palette12)
        self.project.setFont(font)
        self.project.setLayoutDirection(Qt.RightToLeft)
        self.project.setFrameShape(QFrame.NoFrame)
        self.project.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.project.setMargin(3)
        self.project.setIndent(-1)

        self.gridLayout.addWidget(self.project, 0, 0, 1, 1)


        self.horizontalLayout_2.addLayout(self.gridLayout)


        self.verticalLayout.addLayout(self.horizontalLayout_2)


        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.update_filetree_btn = QPushButton(Nuki)
        self.update_filetree_btn.setObjectName(u"update_filetree_btn")
        self.update_filetree_btn.setGeometry(QRect(20, 520, 158, 35))
        self.update_filetree_btn.setMinimumSize(QSize(158, 0))
        self.update_filetree_btn.setMaximumSize(QSize(200, 16777215))
        palette13 = QPalette()
        brush8 = QBrush(QColor(237, 141, 32, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        self.update_filetree_btn.setPalette(palette13)
        font4 = QFont()
        font4.setFamily(u"Cantarell")
        font4.setPointSize(11)
        font4.setBold(True)
        font4.setWeight(75)
        self.update_filetree_btn.setFont(font4)
        self.update_filetree_btn.setStyleSheet(u"QPushButton:hover {\n"
"border-style: outset;\n"
"border-radius: 5px;\n"
"border: 3px solid rgb(238, 173, 83);\n"
"}\n"
"")
        self.circularProgressBarBase = QFrame(Nuki)
        self.circularProgressBarBase.setObjectName(u"circularProgressBarBase")
        self.circularProgressBarBase.setGeometry(QRect(1050, 30, 170, 170))
        self.circularProgressBarBase.setFrameShape(QFrame.NoFrame)
        self.circularProgressBarBase.setFrameShadow(QFrame.Raised)
        self.circularProgress = QFrame(self.circularProgressBarBase)
        self.circularProgress.setObjectName(u"circularProgress")
        self.circularProgress.setGeometry(QRect(10, 10, 150, 150))
        self.circularProgress.setStyleSheet(u"QFrame{\n"
"	background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(206, 92, 0, 0), stop:0.750 rgba(237, 141, 32, 255));\n"
"	border-radius:75px;\n"
"}")
        self.circularProgress.setFrameShape(QFrame.NoFrame)
        self.circularProgress.setFrameShadow(QFrame.Raised)
        self.circularBg = QFrame(self.circularProgressBarBase)
        self.circularBg.setObjectName(u"circularBg")
        self.circularBg.setGeometry(QRect(10, 10, 150, 150))
        self.circularBg.setStyleSheet(u"QFrame{\n"
"	border-radius: 75px;\n"
"	background-color: rgba(53, 53, 53,120)\n"
"}")
        self.circularBg.setFrameShape(QFrame.NoFrame)
        self.circularBg.setFrameShadow(QFrame.Raised)
        self.container = QFrame(self.circularProgressBarBase)
        self.container.setObjectName(u"container")
        self.container.setGeometry(QRect(20, 20, 130, 130))
        self.container.setStyleSheet(u"QFrame{\n"
"	border-radius: 65px;\n"
"	background-color: rgb(53, 53, 53)\n"
"}")
        self.container.setFrameShape(QFrame.StyledPanel)
        self.container.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.container)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 10, 141, 111))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.label.setPalette(palette14)
        font5 = QFont()
        font5.setFamily(u"Noto Sans CJK HK")
        font5.setPointSize(20)
        self.label.setFont(font5)
        self.label.setStyleSheet(u"background-color:none;")
        self.label.setAlignment(Qt.AlignCenter)
        self.circularBg.raise_()
        self.circularProgress.raise_()
        self.container.raise_()
        self.reload_btn = QPushButton(Nuki)
        self.reload_btn.setObjectName(u"reload_btn")
        self.reload_btn.setGeometry(QRect(1080, 220, 120, 32))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.reload_btn.setPalette(palette15)
        font6 = QFont()
        font6.setBold(True)
        font6.setWeight(75)
        self.reload_btn.setFont(font6)
        self.layoutWidget_2 = QWidget(Nuki)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(960, 10, 108, 22))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.tasks_label = QLabel(self.layoutWidget_2)
        self.tasks_label.setObjectName(u"tasks_label")
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush)
        brush9 = QBrush(QColor(255, 255, 255, 128))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
#endif
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        self.tasks_label.setPalette(palette16)

        self.horizontalLayout.addWidget(self.tasks_label)

        self.tasks_num_label = QLabel(self.layoutWidget_2)
        self.tasks_num_label.setObjectName(u"tasks_num_label")
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        self.tasks_num_label.setPalette(palette17)

        self.horizontalLayout.addWidget(self.tasks_num_label)

        self.filetree = QTreeView(Nuki)
        self.filetree.setObjectName(u"filetree")
        self.filetree.setGeometry(QRect(10, 10, 171, 501))
        self.layoutWidget1 = QWidget(Nuki)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(960, 270, 351, 291))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.task_table = QTableView(Nuki)
        self.task_table.setObjectName(u"task_table")
        palette18 = QPalette()
        brush10 = QBrush(QColor(136, 138, 133, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush10)
        brush11 = QBrush(QColor(191, 64, 64, 0))
        brush11.setStyle(Qt.SolidPattern)
        palette18.setBrush(QPalette.Active, QPalette.Highlight, brush11)
        palette18.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush10)
        palette18.setBrush(QPalette.Inactive, QPalette.Highlight, brush11)
        palette18.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.Highlight, brush11)
        palette18.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        self.task_table.setPalette(palette18)
        font7 = QFont()
        font7.setFamily(u"Carlito")
        font7.setPointSize(10)
        font7.setBold(True)
        font7.setWeight(75)
        self.task_table.setFont(font7)
        self.task_table.setFocusPolicy(Qt.NoFocus)
        self.task_table.setLayoutDirection(Qt.LeftToRight)
        self.task_table.setStyleSheet(u"")
        self.task_table.setFrameShape(QFrame.StyledPanel)
        self.task_table.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.task_table.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.task_table.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.task_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.task_table.setDragEnabled(True)
        self.task_table.setDragDropMode(QAbstractItemView.DragDrop)
        self.task_table.setDefaultDropAction(Qt.MoveAction)
        self.task_table.setAlternatingRowColors(True)
        self.task_table.setSelectionMode(QAbstractItemView.MultiSelection)
        self.task_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.task_table.setSortingEnabled(True)
        self.task_table.horizontalHeader().setVisible(True)
        self.task_table.horizontalHeader().setCascadingSectionResizes(False)
        self.task_table.horizontalHeader().setMinimumSectionSize(10)
        self.task_table.horizontalHeader().setProperty("showSortIndicator", True)
        self.task_table.verticalHeader().setVisible(False)
        self.task_table.verticalHeader().setCascadingSectionResizes(True)

        self.verticalLayout_3.addWidget(self.task_table)

        self.opennuke_btn = QPushButton(self.layoutWidget1)
        self.opennuke_btn.setObjectName(u"opennuke_btn")
        sizePolicy1.setHeightForWidth(self.opennuke_btn.sizePolicy().hasHeightForWidth())
        self.opennuke_btn.setSizePolicy(sizePolicy1)
        self.opennuke_btn.setMaximumSize(QSize(600, 16777215))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.Button, brush8)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        self.opennuke_btn.setPalette(palette19)
        self.opennuke_btn.setFont(font6)
        self.opennuke_btn.setStyleSheet(u"QPushButton:hover {\n"
"border-style: outset;\n"
"border-radius: 5px;\n"
"border: 3px solid rgb(238, 173, 83);\n"
"}\n"
"")

        self.verticalLayout_3.addWidget(self.opennuke_btn)


        self.retranslateUi(Nuki)

        QMetaObject.connectSlotsByName(Nuki)
    # setupUi

    def retranslateUi(self, Nuki):
        Nuki.setWindowTitle(QCoreApplication.translate("Nuki", u"Nuki-manage", None))
        self.assigned_shot_label.setText(QCoreApplication.translate("Nuki", u"Assigned shot", None))
        self.assigned_shot_num.setText(QCoreApplication.translate("Nuki", u"TextLabel", None))
        self.sorted_label.setText(QCoreApplication.translate("Nuki", u"Sorted By", None))
        self.sorted_comboBox.setItemText(0, QCoreApplication.translate("Nuki", u"Name", None))
        self.sorted_comboBox.setItemText(1, QCoreApplication.translate("Nuki", u"Due date", None))
        self.sorted_comboBox.setItemText(2, QCoreApplication.translate("Nuki", u"Priority", None))

        self.thumbnail_label.setText(QCoreApplication.translate("Nuki", u"thumbnail", None))
        self.label_shot.setText("")
        self.revision.setText(QCoreApplication.translate("Nuki", u"REVISION", None))
        self.resolution.setText(QCoreApplication.translate("Nuki", u"RESOLUTION", None))
        self.label_frame_in.setText("")
        self.label_frame_out.setText("")
        self.label_resolution.setText("")
        self.label_proj.setText("")
        self.frame_range.setText(QCoreApplication.translate("Nuki", u"FRAME RANGE", None))
        self.label_fps.setText("")
        self.label_seq.setText("")
        self.label_revision.setText("")
        self.sequence.setText(QCoreApplication.translate("Nuki", u"SEQUENCE", None))
        self.shot.setText(QCoreApplication.translate("Nuki", u"SHOT", None))
        self.fps.setText(QCoreApplication.translate("Nuki", u"FPS", None))
        self.project.setText(QCoreApplication.translate("Nuki", u"PROJECT", None))
        self.update_filetree_btn.setText(QCoreApplication.translate("Nuki", u"Update Filetree", None))
        self.label.setText(QCoreApplication.translate("Nuki", u"<p><span style=\" font-size:28pt;\">0</span><span style=\" vertical-align:super;\">%</span></p>", None))
        self.reload_btn.setText(QCoreApplication.translate("Nuki", u"Reload", None))
        self.tasks_label.setText(QCoreApplication.translate("Nuki", u"Tasks", None))
        self.tasks_num_label.setText(QCoreApplication.translate("Nuki", u"0/0", None))
        self.opennuke_btn.setText(QCoreApplication.translate("Nuki", u"Project setting in Nuke", None))
    # retranslateUi

