# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'upload_widget.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Upload(object):
    def setupUi(self, Upload):
        if not Upload.objectName():
            Upload.setObjectName(u"Upload")
        Upload.setWindowModality(Qt.NonModal)
        Upload.resize(906, 559)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Upload.sizePolicy().hasHeightForWidth())
        Upload.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(53, 53, 53, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        Upload.setPalette(palette)
        self.dir_lineedit = QLineEdit(Upload)
        self.dir_lineedit.setObjectName(u"dir_lineedit")
        self.dir_lineedit.setGeometry(QRect(20, 510, 701, 31))
        palette1 = QPalette()
        brush2 = QBrush(QColor(238, 238, 236, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush3 = QBrush(QColor(85, 87, 83, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        brush4 = QBrush(QColor(237, 141, 32, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush4)
        brush5 = QBrush(QColor(238, 238, 236, 128))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        brush6 = QBrush(QColor(146, 148, 149, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        brush7 = QBrush(QColor(53, 132, 228, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        brush8 = QBrush(QColor(46, 52, 54, 128))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.dir_lineedit.setPalette(palette1)
        font = QFont()
        font.setPointSize(10)
        self.dir_lineedit.setFont(font)
        self.layoutWidget = QWidget(Upload)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(730, 150, 161, 241))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.comment_plaintextedit = QPlainTextEdit(self.layoutWidget)
        self.comment_plaintextedit.setObjectName(u"comment_plaintextedit")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.comment_plaintextedit.setPalette(palette2)
        font1 = QFont()
        font1.setPointSize(9)
        self.comment_plaintextedit.setFont(font1)
        self.comment_plaintextedit.setPlaceholderText(u"")

        self.verticalLayout.addWidget(self.comment_plaintextedit)

        self.layoutWidget_2 = QWidget(Upload)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(730, 410, 161, 87))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.select_all_btn = QPushButton(self.layoutWidget_2)
        self.select_all_btn.setObjectName(u"select_all_btn")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush4)
        brush9 = QBrush(QColor(0, 0, 0, 25))
        brush9.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush9)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush9)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush10 = QBrush(QColor(206, 92, 0, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush10)
        brush11 = QBrush(QColor(146, 148, 149, 128))
        brush11.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush9)
        brush12 = QBrush(QColor(238, 236, 234, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.select_all_btn.setPalette(palette3)
        font2 = QFont()
        font2.setFamily(u"Noto Sans CJK JP")
        font2.setPointSize(11)
        font2.setBold(False)
        font2.setWeight(50)
        self.select_all_btn.setFont(font2)

        self.verticalLayout_2.addWidget(self.select_all_btn)

        self.upload_btn = QPushButton(self.layoutWidget_2)
        self.upload_btn.setObjectName(u"upload_btn")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush9)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush9)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.upload_btn.setPalette(palette4)
        self.upload_btn.setFont(font2)

        self.verticalLayout_2.addWidget(self.upload_btn)

        self.status_combo = QComboBox(Upload)
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.setObjectName(u"status_combo")
        self.status_combo.setGeometry(QRect(730, 70, 161, 38))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        self.status_combo.setPalette(palette5)
        self.comment_lineedit = QLineEdit(Upload)
        self.comment_lineedit.setObjectName(u"comment_lineedit")
        self.comment_lineedit.setGeometry(QRect(730, 110, 159, 36))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.comment_lineedit.setPalette(palette6)
        self.comment_lineedit.setFont(font)
        self.comment_lineedit.setEchoMode(QLineEdit.Normal)
        self.comment_lineedit.setAlignment(Qt.AlignCenter)
        self.comment_lineedit.setDragEnabled(False)
        self.comment_lineedit.setReadOnly(True)
        self.comment_lineedit.setClearButtonEnabled(False)
        self.exr_list = QListView(Upload)
        self.exr_list.setObjectName(u"exr_list")
        self.exr_list.setGeometry(QRect(480, 20, 241, 481))
        palette7 = QPalette()
        brush13 = QBrush(QColor(46, 52, 54, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush13)
        brush14 = QBrush(QColor(69, 69, 69, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush14)
        palette7.setBrush(QPalette.Active, QPalette.Highlight, brush4)
        brush15 = QBrush(QColor(46, 52, 54, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush15)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush13)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush14)
        palette7.setBrush(QPalette.Inactive, QPalette.Highlight, brush4)
        brush16 = QBrush(QColor(46, 52, 54, 128))
        brush16.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush16)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        brush17 = QBrush(QColor(46, 52, 54, 128))
        brush17.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush17)
#endif
        self.exr_list.setPalette(palette7)
        self.treeView = QTreeView(Upload)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(20, 20, 450, 481))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Text, brush13)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush14)
        palette8.setBrush(QPalette.Active, QPalette.Highlight, brush4)
        brush18 = QBrush(QColor(46, 52, 54, 128))
        brush18.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush13)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush14)
        palette8.setBrush(QPalette.Inactive, QPalette.Highlight, brush4)
        brush19 = QBrush(QColor(46, 52, 54, 128))
        brush19.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush19)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        brush20 = QBrush(QColor(46, 52, 54, 128))
        brush20.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush20)
#endif
        self.treeView.setPalette(palette8)
        self.upload_msg_label = QLabel(Upload)
        self.upload_msg_label.setObjectName(u"upload_msg_label")
        self.upload_msg_label.setGeometry(QRect(730, 510, 151, 31))
        self.upload_msg_label.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Upload)

        QMetaObject.connectSlotsByName(Upload)
    # setupUi

    def retranslateUi(self, Upload):
        Upload.setWindowTitle(QCoreApplication.translate("Upload", u"Nuki-manage", None))
        self.dir_lineedit.setText("")
        self.comment_plaintextedit.setPlainText("")
        self.select_all_btn.setText(QCoreApplication.translate("Upload", u"Select ALL", None))
        self.upload_btn.setText(QCoreApplication.translate("Upload", u"Upload", None))
        self.status_combo.setItemText(0, QCoreApplication.translate("Upload", u"TODO", None))
        self.status_combo.setItemText(1, QCoreApplication.translate("Upload", u"Done", None))
        self.status_combo.setItemText(2, QCoreApplication.translate("Upload", u"Ready", None))
        self.status_combo.setItemText(3, QCoreApplication.translate("Upload", u"Retake", None))
        self.status_combo.setItemText(4, QCoreApplication.translate("Upload", u"WFA", None))
        self.status_combo.setItemText(5, QCoreApplication.translate("Upload", u"WIP", None))

        self.comment_lineedit.setText(QCoreApplication.translate("Upload", u"POST COMMENT", None))
        self.upload_msg_label.setText(QCoreApplication.translate("Upload", u"Upload Successfully", None))
    # retranslateUi

