# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'upload.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(892, 556)
        palette = QPalette()
        brush = QBrush(QColor(238, 238, 236, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush1 = QBrush(QColor(53, 53, 53, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush2 = QBrush(QColor(237, 141, 32, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        brush3 = QBrush(QColor(238, 238, 236, 128))
        brush3.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        brush4 = QBrush(QColor(146, 148, 149, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        brush5 = QBrush(QColor(53, 132, 228, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush5)
        brush6 = QBrush(QColor(46, 52, 54, 128))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.treeView = QTreeView(self.centralwidget)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(10, 10, 450, 481))
        palette1 = QPalette()
        brush7 = QBrush(QColor(46, 52, 54, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush7)
        brush8 = QBrush(QColor(85, 87, 83, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush8)
        brush9 = QBrush(QColor(69, 69, 69, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush9)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        brush10 = QBrush(QColor(46, 52, 54, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        brush11 = QBrush(QColor(46, 52, 54, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Highlight, brush5)
        brush12 = QBrush(QColor(46, 52, 54, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.treeView.setPalette(palette1)
        self.exr_list = QListView(self.centralwidget)
        self.exr_list.setObjectName(u"exr_list")
        self.exr_list.setGeometry(QRect(470, 10, 241, 481))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush9)
        brush13 = QBrush(QColor(46, 52, 54, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush13)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        brush14 = QBrush(QColor(46, 52, 54, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush14)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        brush15 = QBrush(QColor(46, 52, 54, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush15)
#endif
        self.exr_list.setPalette(palette2)
        self.dir_lineedit = QLineEdit(self.centralwidget)
        self.dir_lineedit.setObjectName(u"dir_lineedit")
        self.dir_lineedit.setGeometry(QRect(10, 500, 701, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Base, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.dir_lineedit.setPalette(palette3)
        self.upload_msg_label = QLabel(self.centralwidget)
        self.upload_msg_label.setObjectName(u"upload_msg_label")
        self.upload_msg_label.setGeometry(QRect(720, 500, 151, 31))
        self.upload_msg_label.setAlignment(Qt.AlignCenter)
        self.reload_btn = QPushButton(self.centralwidget)
        self.reload_btn.setObjectName(u"reload_btn")
        self.reload_btn.setGeometry(QRect(730, 10, 131, 31))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush8)
        brush16 = QBrush(QColor(0, 0, 0, 25))
        brush16.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush16)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        brush17 = QBrush(QColor(255, 255, 255, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush17)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush18 = QBrush(QColor(206, 92, 0, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush18)
        brush19 = QBrush(QColor(146, 148, 149, 128))
        brush19.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush16)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush17)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush18)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.reload_btn.setPalette(palette4)
        font = QFont()
        font.setPointSize(12)
        self.reload_btn.setFont(font)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(720, 160, 161, 241))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.comment_lineedit = QLineEdit(self.layoutWidget)
        self.comment_lineedit.setObjectName(u"comment_lineedit")
        font1 = QFont()
        font1.setPointSize(10)
        self.comment_lineedit.setFont(font1)
        self.comment_lineedit.setEchoMode(QLineEdit.Normal)
        self.comment_lineedit.setAlignment(Qt.AlignCenter)
        self.comment_lineedit.setDragEnabled(False)
        self.comment_lineedit.setReadOnly(True)
        self.comment_lineedit.setClearButtonEnabled(False)

        self.verticalLayout.addWidget(self.comment_lineedit)

        self.comment_plaintextedit = QPlainTextEdit(self.layoutWidget)
        self.comment_plaintextedit.setObjectName(u"comment_plaintextedit")
        font2 = QFont()
        font2.setPointSize(9)
        self.comment_plaintextedit.setFont(font2)
        self.comment_plaintextedit.setPlaceholderText(u"")

        self.verticalLayout.addWidget(self.comment_plaintextedit)

        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(738, 406, 121, 82))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.select_all_btn = QPushButton(self.layoutWidget1)
        self.select_all_btn.setObjectName(u"select_all_btn")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush16)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush18)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.select_all_btn.setPalette(palette5)
        font3 = QFont()
        font3.setFamily(u"Cantarell")
        font3.setPointSize(12)
        font3.setBold(False)
        font3.setWeight(50)
        self.select_all_btn.setFont(font3)

        self.verticalLayout_2.addWidget(self.select_all_btn)

        self.upload_btn = QPushButton(self.layoutWidget1)
        self.upload_btn.setObjectName(u"upload_btn")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush16)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush16)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush16)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush18)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush18)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush6)
#endif
        self.upload_btn.setPalette(palette6)
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setWeight(75)
        self.upload_btn.setFont(font4)

        self.verticalLayout_2.addWidget(self.upload_btn)

        self.status_combo = QComboBox(self.centralwidget)
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.addItem("")
        self.status_combo.setObjectName(u"status_combo")
        self.status_combo.setGeometry(QRect(720, 120, 161, 38))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.dir_lineedit.setText("")
        self.upload_msg_label.setText(QCoreApplication.translate("MainWindow", u"Upload Successfully", None))
        self.reload_btn.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.comment_lineedit.setText(QCoreApplication.translate("MainWindow", u"POST COMMENT", None))
        self.comment_plaintextedit.setPlainText("")
        self.select_all_btn.setText(QCoreApplication.translate("MainWindow", u"Select ALL", None))
        self.upload_btn.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
        self.status_combo.setItemText(0, QCoreApplication.translate("MainWindow", u"TODO", None))
        self.status_combo.setItemText(1, QCoreApplication.translate("MainWindow", u"Done", None))
        self.status_combo.setItemText(2, QCoreApplication.translate("MainWindow", u"Ready", None))
        self.status_combo.setItemText(3, QCoreApplication.translate("MainWindow", u"Retake", None))
        self.status_combo.setItemText(4, QCoreApplication.translate("MainWindow", u"WFA", None))
        self.status_combo.setItemText(5, QCoreApplication.translate("MainWindow", u"WIP", None))

    # retranslateUi

